site_name: RADView Documentation
site_description: The latest product documentation for RADView.


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections

nav:
  - Home: index.md
  - Installation: installation.md 
  - Quick Start: quickstart.md
  - Analytics:
    - Introduction: analytics-user-guide/introduction.md
    - WebLOAD Analytics System Overview: analytics-user-guide/overview.md
    - Getting Started: analytics-user-guide/getting_started.md
    - Generating Charts: analytics-user-guide/generating_charts.md
    - Changing Chart Settings: analytics-user-guide/changing_chart_settings.md
    - Generating Reports: analytics-user-guide/generating_reports.md
    - Working with Load Sessions: analytics-user-guide/load_sessions.md
    - Working with Templates: analytics-user-guide/templates.md
    - Working with Portfolios: analytics-user-guide/portfolios.md
    - Defining Your Preferences: analytics-user-guide/defining_preferences.md
    - Appendix A. WebLOAD Analytics File System Structure: analytics-user-guide/appendix_a.md
    - Appendix B. Understanding the Statistics: analytics-user-guide/appendix_b.md
    - Appendix C. Running Analytics in Command Line Mode: analytics-user-guide/appendix_c.md
    - Appendix D. Understanding the Templates: analytics-user-guide/appendix_d.md
    - Appendix E. Glossary: analytics-user-guide/glossary.md
  - Dashboard:
    - Introduction: dashboard-user-guide/introduction.md
    - Installation: dashboard-user-guide/installation.md
    - Getting Started: dashboard-user-guide/getting_started.md
    - Managing Test: dashboard-user-guide/manage_tests.md
    - Managing Sessions: dashboard-user-guide/manage_sessions.md
    - Managing Resources: dashboard-user-guide/managing_resources.md
    - Using Dashboards: dashboard-user-guide/using_dashboards.md
    - Customizing a Dashboard: dashboard-user-guide/customizing_dashboard.md
    - Managing Dashboards: dashboard-user-guide/managing_dashboards.md
    - Sharing a Dashboard or Panel: dashboard-user-guide/sharing_dashboards.md
    - Creating and Playing a Playlist: dashboard-user-guide/creating_playlist.md
    - Managing Load Generators: dashboard-user-guide/managing_load_generators.md
    - Managing Organizations, Users, and Admins: dashboard-user-guide/managing_organizations.md
    - Appendix A - Editing WebLOAD Dashboard Configuration: dashboard-user-guide/appendix_a.md
  - Recorder:
    - Introduction: recorder-user-guide/introduction.md
    - Overview: recorder-user-guide/overview.md
    - Before you Begin: recorder-user-guide/before_you_begin.md
    - QuickStart: recorder-user-guide/quick_start.md
    - Recording Scripts: recorder-user-guide/recording_scripts.md
    - Editing Scripts: recorder-user-guide/editing_scripts.md
    - Correlating Scripts: recorder-user-guide/correlating_scripts.md
    - Running and Debugging Scripts: recorder-user-guide/running_debugging_scripts.md
    - Working with GIT: recorder-user-guide/working_with_git.md
    - Configuring the WebLOAD Recorder Options: recorder-user-guide/configuring_recorder_options.md
    - Appendix A - The WebLOAD Recorder Toolbox Set: recorder-user-guide/appendix_a.md
    - Appendix B - WebLOAD Recorder File Types: recorder-user-guide/appendix_b.md
    - Appendix C - Launching WebLOAD Recorder: recorder-user-guide/appendix_c.md
    - Appendix D - Converting Certificate Files: recorder-user-guide/appendix_d.md
    - Appendix E - Recording Mobile Applications: recorder-user-guide/appendix_e.md
    - Appendix F - Integrating with Perfecto Mobile: recorder-user-guide/appendix_f.md
    - Appendix G - Selenium Integration: recorder-user-guide/appendix_g.md
    - Appendix H - Glossary: recorder-user-guide/appendix_h.md
  - Scripting:
    - Introduction: scripting-guide/introduction.md
    - Programming your JavaScript Script: scripting-guide/programming_your_javascript.md
    - Advanced JavaScript Script Features: scripting-guide/advanced_javascript_features.md
    - Working with HTTP Protocol: scripting-guide/working_with_http.md
    - Using Asynchronous Requests: scripting-guide/using_asynchronous.md
    - Appendix A - Scripting Samples: scripting-guide/appendix_a.md
    - Appendix B - LiveConnect Overview: scripting-guide/appendix_b.md
  - Automation:
    - Introduction: automation-guide/introduction.md
    - Overview: automation-guide/overview.md
    - Running WebLOAD from the Command Line: automation-guide/webload_cli.md
    - Running WebLOAD in Jenkins: automation-guide/webload_jenkins.md
    - Running WebLOAD Using the OpenAPI: automation-guide/webload_openapi.md
    



  

